# Generated by Django 3.2.4 on 2021-10-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default='No Description')),
                ('private_mode', models.BooleanField(default=False)),
            ],
        ),
    ]
