# Generated by Django 3.2.8 on 2021-10-25 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='private_mode',
            new_name='unlisted',
        ),
    ]
