# Generated by Django 3.2.8 on 2021-11-25 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
    ]
